import { A } from "@/components/ui";
import { Callout, Code, CodeBlock, H1, H2, H3, OL, P, Table, UL } from "@/components/docs";

export default function DeployArc() {
  return (
    <>
      <H1 kicker="GUIDES">Deploy to Arc</H1>
      <P>
        This is the full path from a local setup to Verid anchoring and settling on a real Arc network. Do it on <b style={{ color: "#E8ECE9", fontWeight: 500 }}>Arc Testnet first</b>: it costs nothing, uses the same steps as Mainnet, and proves the whole system. Every step has a script that checks your work, and none of them ever prints a private key.
      </P>
      <Callout title="WHO HOLDS WHICH KEY">
        You hold the <b>deployer</b> key, in an encrypted Foundry keystore that you create and unlock yourself. Verid’s scripts never see it. The two <b>server keys</b> (relayer and validator) are generated by <Code>pnpm arc:keys</Code> into a git-ignored file and are never displayed. Use a separate <b>owner</b> address (ideally a multisig) for the contracts, not the deployer.
      </Callout>

      <H2>What gets deployed, and the roles</H2>
      <Table
        head={["PIECE", "WHAT IT IS", "WHO CONTROLS IT"]}
        cols="minmax(150px,0.8fr) minmax(0,1.6fr) minmax(0,1.4fr)"
        rows={[
          [<Code key="1">VeridRegistry</Code>, "Append-only anchors of receipt fingerprints.", "Owner; only allow-listed anchorers can write."],
          [<Code key="2">VeridValidation</Code>, "Write-once validation outcomes.", "Owner; only registered validators can write."],
          [<Code key="3">VeridEscrow</Code>, "USDC escrow that releases on Pass + anchor.", "No one. No owner or admin."],
          ["Relayer key", "Server key that sends anchoring and settlement transactions.", "You (server secret). Needs a little USDC for gas."],
          ["Validator key", "Server key that writes validation records.", "You (server secret). Needs a little USDC for gas."],
          ["Owner address", "Owns the registry and validation contracts.", "You or your multisig."],
        ]}
      />

      <H2>Step by step (testnet)</H2>
      <OL>
        <li>
          <b>Check the network.</b> Re-read Arc’s official parameters at <a href="https://docs.arc.io" style={{ color: "#4ADE80" }}>docs.arc.io</a>. Verid’s presets match them as of the last check (testnet chain ID 5042002, RPC <Code>https://rpc.testnet.arc.io</Code>, USDC <Code>0x3600…0000</Code> with 6 decimals as ERC-20 and 18 as native gas, minimum fee 20 gwei).
        </li>
        <li>
          <b>Generate the server keys.</b>
          <CodeBlock>{`pnpm arc:keys`}</CodeBlock>
          It prints the relayer and validator <i>addresses</i> and saves the keys to <Code>.arc-secrets/testnet.json</Code>. It refuses to overwrite existing keys.
        </li>
        <li>
          <b>Create your deployer keystore</b> and note its address. You type the key; it is stored encrypted under a password you choose.
          <CodeBlock>{`cast wallet import verid-deployer --interactive
cast wallet address --account verid-deployer`}</CodeBlock>
        </li>
        <li>
          <b>Fund three addresses</b> with testnet USDC from the Circle faucet at <a href="https://faucet.circle.com" style={{ color: "#4ADE80" }}>faucet.circle.com</a>: the deployer (about 0.11 USDC for the deploy), the relayer and the validator (about 0.02 each for operations). Arc pays gas in USDC, so there is no separate gas token.
        </li>
        <li>
          <b>Run the readiness check.</b> It is read-only and tells you exactly what is missing.
          <CodeBlock>{`pnpm arc:doctor --deployer 0xYourDeployerAddress`}</CodeBlock>
          It confirms the RPC is the chain you asked for, the fee floor, the USDC contract, that the contracts are built (<Code>forge build</Code> in <Code>contracts/</Code>), and that each address has enough gas.
        </li>
        <li>
          <b>Get your deploy commands.</b> This prints them; it sends nothing.
          <CodeBlock>{`pnpm arc:deploy-plan --owner 0xYourOwnerOrMultisig`}</CodeBlock>
          Run what it prints (it sets <Code>VERID_OWNER</Code>, <Code>VERID_ANCHORER</Code>, <Code>VERID_VALIDATOR</Code>, <Code>VERID_USDC</Code> and calls <Code>forge script</Code> with your keystore and <Code>--broadcast</Code>). The deploy script itself was dry-run against live Arc testnet state and uses about 3.4 million gas, roughly 0.10 USDC at 30 gwei.
        </li>
        <li>
          <b>Accept ownership.</b> The deploy starts a two-step handoff. The owner address calls <Code>acceptOwnership()</Code> on <Code>VeridRegistry</Code> and <Code>VeridValidation</Code>. Until then the deployer still owns them; the doctor reminds you.
        </li>
        <li>
          <b>Check the wiring.</b>
          <CodeBlock>{`pnpm arc:doctor`}</CodeBlock>
          After a deploy it also confirms the relayer is allow-listed, the validator is registered, and the escrow points at the right token, validation contract and registry.
        </li>
        <li>
          <b>Point the app at Arc.</b>
          <CodeBlock>{`pnpm arc:configure`}</CodeBlock>
          This reads the deployed addresses from Foundry’s broadcast output and writes them, with the server keys, into <Code>apps/web/.env.local</Code>, replacing the local dev-chain settings. Restart the app.
        </li>
        <li>
          <b>Prove it end to end.</b>
          <CodeBlock>{`pnpm arc:smoke --escrow`}</CodeBlock>
          This sends real testnet transactions: records a validation, anchors a labelled synthetic receipt, verifies it by reading <i>only the chain</i>, then funds a 0.01 USDC escrow and releases it. If it prints <Code>SMOKE TEST PASSED</Code>, anchoring, verification and settlement all work on Arc.
        </li>
      </OL>

      <H2>Rehearse on your machine first (no money)</H2>
      <P>
        Every script accepts <Code>--network local</Code>, which runs the identical flow against your local test chain (<Code>pnpm dev:chain</Code>) so you can practise the commands before touching a real network. It needs <Code>VERID_USDC</Code> set to a 6-decimal token on that chain (the dev chain’s test USDC works). The local chain is not Arc; this rehearses the procedure, not Arc’s behaviour.
      </P>

      <H2>Troubleshooting</H2>
      <Table
        head={["SYMPTOM", "CAUSE AND FIX"]}
        cols="minmax(0,1fr) minmax(0,2fr)"
        rows={[
          ["A transaction never shows up", "Arc silently drops transactions priced below its 20 gwei floor. Verid’s own transactions are clamped above it; for the Foundry deploy keep --with-gas-price at 30gwei or the doctor’s suggested fee."],
          ["The doctor says the RPC reports another chain", "You pointed at the wrong network. Do not continue; fix the URL. The server also refuses to send anything when the chain ID does not match."],
          ["Balances look wrong by a factor of 10¹²", "Native gas balances use 18 decimals; the USDC ERC-20 interface uses 6. Never mix them. The scripts keep them apart."],
          ["Escrow release says not releasable", "It needs a registered validator’s Pass on VeridValidation and the anchor on VeridRegistry. Run the doctor to confirm the validator is registered and the relayer is an anchorer."],
          ["Anchoring says unavailable in the app", "The app needs ARC_RPC_URL, ARC_CHAIN_ID, VERID_REGISTRY_ADDRESS and VERID_RELAYER_PRIVATE_KEY. Run pnpm arc:configure and restart."],
          ["An intermittent “fetch failed”", "A transient network error reaching the RPC. Re-run; the scripts and server retry where it is safe."],
        ]}
      />

      <H2>Mainnet</H2>
      <P>
        Repeat the same steps with <Code>--network mainnet</Code>. Differences you must respect:
      </P>
      <UL>
        <li><b>It spends real USDC.</b> <Code>arc:configure</Code> and <Code>arc:smoke</Code> refuse to run unless you add <Code>--mainnet-i-am-sure</Code>.</li>
        <li><b>Re-verify the parameters</b> in Arc’s docs right before you deploy. Never reuse a value copied from elsewhere.</li>
        <li><b>The owner should be a multisig or hardware wallet</b>, not a hot key, and the server keys should live in your host’s secret manager, not a file.</li>
        <li><b>Test failure paths first</b> on testnet: a failed validation, a refund, and a reverted transaction.</li>
        <li>Explorer links: on testnet, <Code>https://explorer.testnet.arc.io</Code> is a Blockscout explorer and <Code>/tx/&lt;hash&gt;</Code> was verified to open a transaction page, so set <Code>NEXT_PUBLIC_ARC_EXPLORER_URL</Code> to it. The mainnet explorer’s scheme has not been verified against a real mainnet transaction; check one before setting it.</li>
      </UL>

      <H2>What is verified, and what is not</H2>
      <UL>
        <li>The contracts and every flow are tested on a local standard EVM (anvil), and the deploy script has been dry-run against live Arc testnet state. Stock anvil is <b>not</b> Arc and cannot reproduce Arc-specific behaviour; Arc ships its own Foundry build for that. The smoke test above is what proves it on the real network.</li>
        <li>Nothing here has been run on Arc Mainnet.</li>
      </UL>
      <P>
        See also <A href="/docs/self-hosting" css="color:#4ADE80">Self-hosting &amp; configuration</A> for every environment variable and <A href="/docs/escrow" css="color:#4ADE80">Settlement &amp; escrow</A> for how the escrow behaves.
      </P>
    </>
  );
}
