/**
 * Shared helpers for the Arc deployment scripts (keys, doctor, configure, smoke).
 *
 * SAFETY RULES these scripts follow:
 *  - Private keys are never printed. Only addresses are shown.
 *  - Secrets live in `.arc-secrets/` (git-ignored) or in `apps/web/.env.local` (git-ignored).
 *  - The DEPLOYER key is never handled here at all: use an encrypted Foundry keystore (`cast wallet import`).
 *  - Mainnet actions that spend money need an explicit `--mainnet-i-am-sure` flag.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { createPublicClient, defineChain, http, type Address, type Hex, type PublicClient } from "viem";
import { ARC_MAINNET, ARC_TESTNET, type ArcNetwork } from "../src/config";

export const ROOT = resolve(import.meta.dirname, "../../..");
export const SECRETS_DIR = resolve(ROOT, ".arc-secrets");
export const ENV_FILE = resolve(ROOT, "apps/web/.env.local");

export type NetworkName = "testnet" | "mainnet" | "local";

export function parseArgs(argv: string[]) {
  const flags = new Set<string>();
  const values: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i]!;
    if (!a.startsWith("--")) continue;
    const next = argv[i + 1];
    if (next !== undefined && !next.startsWith("--")) {
      values[a.slice(2)] = next;
      i++;
    } else flags.add(a.slice(2));
  }
  const network = (values.network ?? "testnet") as NetworkName;
  if (network !== "testnet" && network !== "mainnet" && network !== "local") fail(`--network must be testnet, mainnet or local (got "${values.network}")`);
  return { flags, values, network };
}

export function fail(msg: string): never {
  console.error(`\n✕ ${msg}\n`);
  process.exit(1);
}

/**
 * `local` is a REHEARSAL mode against a local anvil (NOT Arc): same scripts, same flow, no real money. It needs
 * VERID_USDC set to a 6-decimal token deployed on that chain (the dev chain's DevUSDC works).
 */
export function presetFor(n: NetworkName): ArcNetwork {
  if (n === "mainnet") return ARC_MAINNET;
  if (n === "testnet") return ARC_TESTNET;
  const usdc = process.env.VERID_USDC;
  if (!usdc || !/^0x[0-9a-fA-F]{40}$/.test(usdc)) fail("--network local needs VERID_USDC set to a 6-decimal token address on your local chain");
  return { name: "local-anvil", chainId: 31337, rpcUrl: process.env.LOCAL_RPC_URL ?? "http://127.0.0.1:8545", explorerUrl: "", usdcAddress: usdc as Address, minMaxFeePerGas: 1_000_000_000n };
}

export function clientFor(net: ArcNetwork, rpcOverride?: string): PublicClient {
  const rpc = rpcOverride ?? net.rpcUrl;
  const chain = defineChain({ id: net.chainId, name: net.name, nativeCurrency: { name: "USDC", symbol: "USDC", decimals: 18 }, rpcUrls: { default: { http: [rpc] } } });
  return createPublicClient({ chain, transport: http(rpc, { timeout: 20_000, retryCount: 2 }) }) as PublicClient;
}

export interface Secrets {
  network: NetworkName;
  chainId: number;
  relayerAddress: Address;
  relayerPrivateKey: Hex;
  validatorAddress: Address;
  validatorPrivateKey: Hex;
  createdAt: string;
}

export const secretsPath = (n: NetworkName) => resolve(SECRETS_DIR, `${n}.json`);

export function loadSecrets(n: NetworkName): Secrets | null {
  const p = secretsPath(n);
  return existsSync(p) ? (JSON.parse(readFileSync(p, "utf8")) as Secrets) : null;
}

export function saveSecrets(s: Secrets) {
  mkdirSync(SECRETS_DIR, { recursive: true });
  writeFileSync(secretsPath(s.network), JSON.stringify(s, null, 2), { mode: 0o600 });
}

export interface Deployed {
  registry?: Address;
  validation?: Address;
  escrow?: Address;
}

/** Read deployed addresses from the latest Foundry broadcast for this chain (contracts/broadcast/Deploy.s.sol/<chainId>/run-latest.json). */
export function deployedFromBroadcast(chainId: number): Deployed {
  const p = resolve(ROOT, `contracts/broadcast/Deploy.s.sol/${chainId}/run-latest.json`);
  if (!existsSync(p)) return {};
  const j = JSON.parse(readFileSync(p, "utf8")) as { transactions?: { transactionType?: string; contractName?: string; contractAddress?: string }[] };
  const pick = (name: string) => j.transactions?.find((t) => t.transactionType === "CREATE" && t.contractName === name)?.contractAddress as Address | undefined;
  return { registry: pick("VeridRegistry"), validation: pick("VeridValidation"), escrow: pick("VeridEscrow") };
}

const BEGIN = (n: string) => `# >>> verid ${n} (generated by arc:configure) >>>`;
const END = (n: string) => `# <<< verid ${n} <<<`;
const escape = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

/** Remove a managed block (any of ours) from an env file's text. */
export function stripBlock(text: string, begin: string, end: string): string {
  return text.replace(new RegExp(`${escape(begin)}[\\s\\S]*?${escape(end)}\\n?`), "").replace(/\n{3,}/g, "\n\n");
}

export function writeEnvBlock(name: string, lines: string[]) {
  let cur = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, "utf8") : "";
  // The local dev chain block defines the same keys; two chains cannot be configured at once.
  cur = stripBlock(cur, "# >>> verid dev-chain (generated; local anvil, NOT Arc) >>>", "# <<< verid dev-chain <<<");
  for (const other of ["arc-testnet", "arc-mainnet"]) cur = stripBlock(cur, BEGIN(other), END(other));
  mkdirSync(dirname(ENV_FILE), { recursive: true });
  writeFileSync(ENV_FILE, `${cur.trimEnd()}\n\n${[BEGIN(name), ...lines, END(name)].join("\n")}\n`);
}

export const short = (a: string) => `${a.slice(0, 8)}…${a.slice(-6)}`;
